[build]
  command = "npm run build"
  publish = "."

[[redirects]]
  from = "/insurance-details"
  to = "/insurance.html"
  status = 301

[[redirects]]
  from = "/insurance-details.html"
  to = "/insurance.html"
  status = 301
